#!/usr/bin/env python3
"""
exp_duality_gate_transfer.py

Reusable META/DUALITA audit for transferring the BOUNDARY_LAYER_GATE.

Question:
    Does the denominator-collapse gate discriminate dipolar duality from
    illusory duality, or does it become a local BOUNDARY metric when moved
    away from GUE/Poisson?

The script builds a controlled layer map between:

- DIPOLARE: a coherent golden/Beatty gap sequence generated by the orbit of
  floor((n + phase) * phi). Its gaps are the symbolic det=-1 D-ND pole in the
  minimal positive alphabet {1, 2}.
- ILLUSORIA: a full random permutation of the same gaps. This preserves the
  one-point distribution and first moment but removes the generating order.

Layer beta replaces a beta fraction of dipolar positions with values from the
illusory permutation. Canonical observables and original-vs-shuffle z gates are
imported from observables_registry.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from observables_registry import (
    OBSERVABLES_CANONICAL,
    OBSERVABLES_REGISTRY_VERSION,
    compute_canonical,
)


OBS_NAMES = list(OBSERVABLES_CANONICAL.keys())
PHI = (1.0 + 5.0**0.5) / 2.0


def dipolar_gaps(n_gaps: int, phase: float) -> np.ndarray:
    """Return coherent golden Beatty gaps in {1, 2}."""
    n = np.arange(n_gaps + 1, dtype=float) + float(phase)
    positions = np.floor(n * PHI).astype(float)
    gaps = np.diff(positions)
    mean = float(np.mean(gaps))
    return gaps / mean if mean > 1e-15 else gaps


def beta_layer_gaps(
    dipolar: np.ndarray,
    beta: float,
    rng: np.random.Generator,
) -> np.ndarray:
    """Replace a beta fraction of coherent positions with a shuffled copy."""
    illusory = rng.permutation(dipolar)
    if beta <= 0.0:
        out = dipolar.copy()
    elif beta >= 1.0:
        out = illusory.copy()
    else:
        mask = rng.random(len(dipolar)) < beta
        out = dipolar.copy()
        out[mask] = illusory[mask]
    mean = float(np.mean(out))
    return out / mean if mean > 1e-15 else out


def z_against_shuffle(
    gaps: np.ndarray,
    n_baseline: int,
    rng: np.random.Generator,
) -> tuple[dict[str, float], dict[str, float], dict[str, float]]:
    """Return original observables, shuffle baseline std, and z scores."""
    original = compute_canonical(gaps)
    baseline_vals = {name: [] for name in OBS_NAMES}
    for _ in range(n_baseline):
        obs = compute_canonical(rng.permutation(gaps))
        for name in OBS_NAMES:
            baseline_vals[name].append(obs[name])

    shuffle_std = {}
    z = {}
    for name in OBS_NAMES:
        vals = np.array(baseline_vals[name], dtype=float)
        mean = float(np.mean(vals))
        sd = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
        shuffle_std[name] = sd
        z[name] = float((original[name] - mean) / sd) if sd > 1e-15 else 0.0
    return original, shuffle_std, z


def vector(row: dict, names: list[str]) -> np.ndarray:
    return np.array([row["observables"][name] for name in names], dtype=float)


def classify_layers(rows: list[dict], obs_names: list[str]) -> dict:
    """Classify layers by standardized distance to dipolar/illusory endpoints."""
    if not obs_names:
        return {
            "observables": [],
            "endpoint_distance": 0.0,
            "layers": {},
            "ambiguous_beta": [],
        }

    by_beta: dict[float, list[dict]] = {}
    for row in rows:
        by_beta.setdefault(float(row["beta"]), []).append(row)

    dip_vectors = np.array([vector(row, obs_names) for row in by_beta[0.0]], dtype=float)
    ill_vectors = np.array([vector(row, obs_names) for row in by_beta[1.0]], dtype=float)
    endpoints = np.vstack([dip_vectors, ill_vectors])
    scale = np.std(endpoints, axis=0, ddof=1)
    scale[scale <= 1e-15] = 1.0
    dip_centroid = np.mean(dip_vectors, axis=0)
    ill_centroid = np.mean(ill_vectors, axis=0)
    endpoint_distance = float(np.linalg.norm((ill_centroid - dip_centroid) / scale))

    layers = {}
    ambiguous_beta = []
    for beta, beta_rows in sorted(by_beta.items()):
        coords = []
        margins = []
        labels = []
        for row in beta_rows:
            x = vector(row, obs_names)
            d_dip = float(np.linalg.norm((x - dip_centroid) / scale))
            d_ill = float(np.linalg.norm((x - ill_centroid) / scale))
            denom = d_dip + d_ill
            coord = float((d_dip - d_ill) / denom) if denom > 1e-15 else 0.0
            margin = float(abs(d_dip - d_ill) / denom) if denom > 1e-15 else 0.0
            coords.append(coord)
            margins.append(margin)
            labels.append("dipolar" if d_dip < d_ill else "illusory")
        ambiguous_fraction = float(np.mean(np.array(margins) < 0.15))
        if ambiguous_fraction >= 0.5:
            ambiguous_beta.append(beta)
        layers[f"{beta:.3f}"] = {
            "coordinate_mean": float(np.mean(coords)),
            "coordinate_std": float(np.std(coords, ddof=1)) if len(coords) > 1 else 0.0,
            "margin_mean": float(np.mean(margins)),
            "ambiguous_fraction": ambiguous_fraction,
            "illusory_label_fraction": float(np.mean(np.array(labels) == "illusory")),
        }

    return {
        "observables": obs_names,
        "endpoint_distance": endpoint_distance,
        "layers": layers,
        "ambiguous_beta": ambiguous_beta,
    }


def summarize_gate(rows: list[dict], z_min: float) -> dict:
    by_beta: dict[float, list[dict]] = {}
    for row in rows:
        by_beta.setdefault(float(row["beta"]), []).append(row)

    layers = {}
    for beta, beta_rows in sorted(by_beta.items()):
        stable_counts = []
        stable_freq = {name: [] for name in OBS_NAMES}
        z_values = {name: [] for name in OBS_NAMES}
        for row in beta_rows:
            stable = [name for name in OBS_NAMES if abs(row["z"][name]) >= z_min]
            stable_counts.append(len(stable))
            for name in OBS_NAMES:
                stable_freq[name].append(1.0 if name in stable else 0.0)
                z_values[name].append(row["z"][name])
        layers[f"{beta:.3f}"] = {
            "stable_count_mean": float(np.mean(stable_counts)),
            "stable_count_std": float(np.std(stable_counts, ddof=1)) if len(stable_counts) > 1 else 0.0,
            "stable_frequency": {name: float(np.mean(vals)) for name, vals in stable_freq.items()},
            "z_mean": {name: float(np.mean(vals)) for name, vals in z_values.items()},
        }

    endpoint_stable = []
    for name in OBS_NAMES:
        endpoint_rows = by_beta[0.0] + by_beta[1.0]
        freq = np.mean([1.0 if abs(row["z"][name]) >= z_min else 0.0 for row in endpoint_rows])
        if freq >= 0.75:
            endpoint_stable.append(name)

    return {
        "z_min": z_min,
        "endpoint_stable_observables": endpoint_stable,
        "layers": layers,
    }


def run(args: argparse.Namespace) -> dict:
    rng = np.random.default_rng(args.seed)
    betas = [float(x) for x in np.linspace(0.0, 1.0, args.n_beta)]
    rows = []

    for rep in range(args.n_replicates):
        phase = float(rng.random())
        base = dipolar_gaps(args.n_gaps, phase)
        for beta in betas:
            layer_rng = np.random.default_rng(rng.integers(0, 2**63 - 1))
            gaps = beta_layer_gaps(base, beta, layer_rng)
            obs, shuffle_std, z = z_against_shuffle(
                gaps,
                n_baseline=args.n_baseline,
                rng=np.random.default_rng(rng.integers(0, 2**63 - 1)),
            )
            rows.append(
                {
                    "replicate": rep,
                    "phase": phase,
                    "beta": beta,
                    "observables": obs,
                    "shuffle_std": shuffle_std,
                    "z": z,
                    "stable_observables": [name for name in OBS_NAMES if abs(z[name]) >= args.z_min],
                }
            )

    gate = summarize_gate(rows, args.z_min)
    all_classification = classify_layers(rows, OBS_NAMES)
    gated_classification = classify_layers(rows, gate["endpoint_stable_observables"])

    output = {
        "experiment": "duality_gate_transfer",
        "category": "gate_transferability",
        "question": "Does the denominator-collapse gate transfer from BOUNDARY to DUALITA_DIPOLARE_VS_ILLUSORIA?",
        "observables_registry": OBSERVABLES_REGISTRY_VERSION,
        "observables_used": OBS_NAMES,
        "params": vars(args),
        "gate": gate,
        "classification_all_observables": all_classification,
        "classification_endpoint_gated": gated_classification,
        "rows": rows,
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        json.dump(output, f, indent=2)

    print(f"observables_registry={OBSERVABLES_REGISTRY_VERSION}")
    print(f"observables_used={OBS_NAMES}")
    print(f"endpoint_stable_observables={gate['endpoint_stable_observables']}")
    print(
        "endpoint_distance_all="
        f"{all_classification['endpoint_distance']:.3f} "
        "endpoint_distance_gated="
        f"{gated_classification['endpoint_distance']:.3f}"
    )
    source = gated_classification if gate["endpoint_stable_observables"] else all_classification
    print("beta stable_count margin ambiguous illusory_fraction")
    for beta in betas:
        key = f"{beta:.3f}"
        stable_count = gate["layers"][key]["stable_count_mean"]
        layer = source["layers"].get(key, {})
        print(
            f"{beta:>4.2f} {stable_count:>12.3f} "
            f"{layer.get('margin_mean', 0.0):>8.3f} "
            f"{layer.get('ambiguous_fraction', 0.0):>9.3f} "
            f"{layer.get('illusory_label_fraction', 0.0):>17.3f}"
        )
    print(f"saved {out_path}")
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n-gaps", type=int, default=4096)
    parser.add_argument("--n-replicates", type=int, default=24)
    parser.add_argument("--n-beta", type=int, default=11)
    parser.add_argument("--n-baseline", type=int, default=40)
    parser.add_argument("--z-min", type=float, default=2.0)
    parser.add_argument("--seed", type=int, default=202605070803)
    parser.add_argument("--out", default="tools/data/duality_gate_transfer.json")
    args = parser.parse_args()
    run(args)


if __name__ == "__main__":
    main()
